site_name: Fundamentos de algoritmos
#repo_url: https://github.com/eversonott/fundamentos-algoritmos
#repo_name: eversonott/fundamentos-algoritmos
edit_uri: tree/main/docs

nav:
  - Início: index.md
  - Módulo 1:
    - Aula 00 - Apresentações 05/04: "Módulo 1/aula_00.md"
    - Aula 01 - Caminhos na computação 12/04: "Módulo 1/aula_01.md"
    - Aula 02 - "Olá Mundo" da computação 19/04: "Módulo 1/aula_02.md"
    - Aula 03 - Variáveis e conveções de nomenclatura 26/04: "Módulo 1/aula_03.md"
    - Aula 04 -  Expressões, instruções e comentários 03/05: "Módulo 1/aula_04.md"
    - Aula 05 - Funções 10/05: "Módulo 1/aula_05.md"
    - Aula 06 - Funções 17/05: "Módulo 1/aula_06.md"
    - Aula 07 - Execução Condicional 24/05: "Módulo 1/aula_07.md"
    - Aula 08 - Recursividade 31/05: "Módulo 1/aula_08.md"
    - Aula 09 - Dúvidas, Revisão e Pensamento Recursivo 07/06: "Módulo 1/aula_09.md"
    - Aula 10 - Introdução à iteração - instrução while, break e continue 14/06: "Módulo 1/aula_10.md"
    - Aula 11 - Strings, Listas e seus Operadores e Métodos 21/06: "Módulo 1/aula_11.md"
    - Aula 12 - Métodos de listas: "Módulo 1/aula_12.md"
    - Aula 13 - Instrução For: "Módulo 1/aula_13.md"
    #- Aula 02 - Variávies, expressões e instruções: "Módulo 1/aula_02.md"
    #- Aula 02: "Módulo 1/aula_02.md"
    #- Aula 03: "Módulo 1/aula_03.md"
    #- Aula 04: "Módulo 1/aula_04.md"
    #- Aula 05: "Módulo 1/aula_05.md"
    #- Aula 06: "Módulo 1/aula_06.md"
    #- Aula 07: "Módulo 1/aula_07.md"
    #- Aula 08: "Módulo 1/aula_08.md"
    #- Aula 09: "Módulo 1/aula_09.md"
    #- Aula 10: "Módulo 1/aula_10.md"
    #- Aula 11: "Módulo 1/aula_11.md"
    #- Aula 12: "Módulo 1/aula_12.md"
theme: 
  name: material
  features:
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  language: pt-BR
  logo: assets/logo_fundamentos_algoritmos.png
  favicon: assets/logo_fundamentos_algoritmos.png
  palette:
    - scheme: slate
      primary: deep blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep blue
      toggle:
        icon: material/weather-night
        name: Modo noturno

markdown_extensions:
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.keys
  - footnotes
  - markdown.extensions.attr_list
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true  
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: ["docs"]
  - tables

plugins:
  - social
  - search
  - macros
  - mkdocs-video
  # - ezlinks:
  #    warn_ambiguities: true
  #    wikilinks:  true
  #    reference_links: true


extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
