site_name: Fundamentos de algoritmos
repo_url: https://github.com/eversonott/fundamentos-algoritmos
repo_name: eversonott/fundamentos-algoritmos
edit_uri: tree/main/docs

theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png


