site_name: Fundamentos de algoritmos
#repo_url: https://github.com/eversonott/fundamentos-algoritmos
#repo_name: eversonott/fundamentos-algoritmos
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR
  logo: assets/logo_fundamentos_algoritmos.png
  favicon: assets/logo_fundamentos_algoritmos.png
  palette:
    - scheme: slate
      primary: deep blue
      toggle:
        icon: material/weather-sunny
        name: Modo claro
    - scheme: default
      primary: deep blue
      toggle:
        icon: material/weather-night
        name: Modo noturno

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true  
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - macros
  - mkdocs-video
  - ezlinks:
      warn_ambiguities: true
      wikilinks:  true
      reference_links: true


extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
