site_name: Fundamentos de algoritmos
repo_url: https://github.com/eversonott/fundamentos-algoritmos
repo_name: eversonott/fundamentos-algoritmos
edit_uri: tree/main/docs

theme: 
  name: readthedocs
  language: pt-BR
  logo: assets/logo_fundamentos_algoritmos.png
  favicon: assets/logo_fundamentos_algoritmos.png

  #markdown_extensions:
  #- attr_list
  #  - pymdownx.highlight:
  #    anchor_linenums: true
  #    line_spans: __span
  #    pygments_lang_class: true
  #- pymdownx.inlinehilite
  #- pymdownx.snippets
  #- pymdownx.superfences
  #- pymdownx.arithmatex:
      generic: true
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
